# Generated by Django 3.2.20 on 2023-10-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20231009_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='prev_status',
            field=models.CharField(choices=[('p', 'Pending'), ('c', 'Completed'), ('e', 'Expired'), ('a', 'Aborted')], default=None, max_length=1, null=True),
        ),
    ]
