# Generated by Django 3.2.20 on 2023-08-22 09:39

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20230822_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=timezone.now),
        ),
    ]
