# Generated by Django 3.2.20 on 2023-08-22 09:40

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(auto_now=True,  default=timezone.now),
        ),
    ]
