# Generated by Django 3.2.20 on 2023-10-04 13:45

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipeingredientimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientimage',
            name='image',
            field=models.ImageField(upload_to=recipes.models.recipe_ingredient_image_upload_handler),
        ),
    ]
